### ISSUE TITLE
Tooling and Examples

### ISSUE THREAD

**Issue by smaxwellstewart** [hueniverse/oz#34]
First off, this is awesome!

As someone that also detests Oauth2, like seriously, I am really happy that we might have a credible way past Oauth2. Hot stuff.

So i have used Hawk Auth before and while I loved it my biggest stumbling point was not being able to use a decent REST client that handled the auth. Do you know of any REST clients that support this new protocol? Alternatively how did you get around this if not? I know unit tests and integration tests go a long way to remove the need for a lot of manual tests but sometimes it is still necessary.

Secondly, can you point me in the direction of implementation examples? I believe [hueniverse/postmile](https://github.com/hueniverse/postmile) is one, though I haven't dug into the code yet. Any others?

**Comment by hueniverse** [comment]
The only tool I am aware of with hawk support is the request module. I don't know of a manual sandbox (though postmile does include a developer console page for just that). Postmile is the only current example of oz but it's out dated. This is on my todo list.

**Comment by smaxwellstewart** [comment]
@hueniverse I can see you've been up to a lot recently so totally understand the lack of examples and kudos for pumping out more awesome open source joy. I would be happy to try and help on the examples front, I am now considering implementing Oz in a user service i am devving called [lummox](https://github.com/smaxwellstewart/lummox).

I am designing it as a microservice, and basically it is respnsible for the bits that Oz leaves out, CRUD of users and authenticating them. I was deliberately not going down the OAuth2 route as I hate it, so was using a JWT auth mechanism with refresh and access tokens. But Oz seems to have similar benefits (possibility of stateless session) with more layers of security.

Anyway be great to see if I could implement it in this project but wandering what's the best place to start understanding it. I imagine just source code for now eh...

**Comment by smaxwellstewart** [comment]
Ok so i think I got my head around the protocol. Going to try and put together a simple example of a server and an app.

Not sure if you wanna close this issue and make 2 different issues, one for examples and one for tooling.

Also I found this postmanlabs/postman-app-support#839 look like a very promising feature for postman which is my go to rest client.

**Comment by ryansobol** [comment]
@smaxwellstewart I'd love to see your examples when they're ready.

**Comment by smaxwellstewart** [comment]
@ryansobol I've been busy completing a related project, so no examples yet. However I will be focusing on this soon.

@hueniverse Seems like there is progress on the postman issue and Hawk auth will soon be added to postman.

**Comment by ryansobol** [comment]
@smaxwellstewart Awesome. BTW, a few weekends ago, I wrote up a little single-file program that implements the basic Oz workflow. It really helped me understand some of the nitty gritty workflow details (and also raised a bunch more questions).

https://github.com/hueniverse/oz/pull/37

**Comment by ryansobol** [comment]
One of the things I really like about the Oz protocol is how flexible it is. After whipping up a [working example in express](#37), the next thing I'd really love to see is an actual server-side app with an Oz implementation that mirrors the OAuth 1.0a server-size workflow.

**Comment by smaxwellstewart** [comment]
So i have had a bit of time to look at things and am trying to put together a working example of an application to server example using scarecrow for hapi.

I started a repo if others want to contribute, [oz-examples](https://github.com/smaxwellstewart/oz-examples), until we have a working example to merge back in to this repo.

Been getting my head around Hawk auth again, and taking the time to try and understand the protocol. Seems like there is a lot of layers of security, which is really good but does demand a fair amount of careful understanding of exactly what protection each is offering.

Having a working rest client for Hawk auth would really speed up dev as well. Last time i checked it had been selected for active dev :)

**Comment by smaxwellstewart** [comment]
Also thank you @ryansobol  your example really helps!

**Comment by mikalai-silivonik** [comment]
For anyone interested I have an example of Oz usage: https://github.com/mikalai-silivonik/hapi-oz-example that does server-to-server auth.

**Comment by kodekrendel** [comment]
Great. Thanks for examples. May be any examples with Hawk also?
