### ISSUE TITLE
Advanced scoping

### ISSUE THREAD

**Issue by mattkrea** [hueniverse/oz#36]
@hueniverse I'm aware this may be somewhat outside the scope of Oz directly but posting here because I've had these issues with OAuth 2.0 at the company I work for and would like to have at least a little discussion will others that are implementing services with the expectation of both outside integration and internal use.

Originally I had implemented an OAuth 2.0 server in Node.js with some custom additions to it (RSA pub/priv key verification, encryption, etc) because the server granting tokens was not also serving up the data / resources. So because this is already something a third party can't implement with any existing OAuth 2 client we decided any third parties will have to implemented something custom which opens up the door for us to explore a bit.

With these additions the implementation would have worked for a couple use cases but really became unwieldy. As it included more and more resources and user types (I'll explain further down) it just became very clear it was not going to work in the long term.

Our use case is somewhat complicated but I have to imagine others in the open source world encounter issues like this as well.

Given resources X, Y, Z which all have sub-resources such as X.profile, X.orderHistory, etc we were looking at ways for user type X, Y, and Z all to login (separate services, single authentication system). To clarify without going into too much detail imagine X as customers, Y as sales reps / resellers, and Z as employees.

X should be able to login directly and view their profile and orderHistory. Simple enough: `[ 'x:profile', 'x:order_history' ]`

Y should be able to login as a sales person and view their profile but *also* details on customers they brought in (this is where it gets complicated). `[ 'y:profile', 'y:x:profile', 'y:x:orderHistory' ]` ? 

This is the problem that I would have to imagine others have faced. I'd be up for writing some sort of validation library that could be used along with Oz but I wanted to sort of throw this out there to see if it was a problem others have seen.

Unfortunately we (the development team at my office) recently took to looking at Amazon's implementation of authentication statements and policies for describing resources but it seems to be far more than we need.

Feel free to close of course if this is something you would rather not even discuss here but if you have any idea where a good forum for this might be I would greatly appreciate directions on where to take this.

Thanks.

Edit: here is a link to the Amazon statements I referred to: http://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html#policies-basic-structure

**Comment by hueniverse** [comment]
I don't think this belongs here. One of the things I am trying to do with Oz is keep things simple at this level. I also not sure that at the end, these kind of complex systems are sustainable. Can't really help with your specific questions, but I would implement that as a separate layer on top of auth, basically it's own service.
