### ISSUE TITLE
2-Legged Workflow

### ISSUE THREAD

**Issue by shawm11** [hueniverse/oz#44]
From what I understand the workflow described in the README is a 3-legged workflow (when there is a third-party involved). To create a 2-legged workflow, is it safe to skip the grant and rsvp steps of the workflow described in the README? The biggest issue I see with a 2-legged workflow is revoking a ticket (or grant).

SIDE NOTE: For those who do not know about or understand the 2-legged, 3-legged, or n-legged workflows, check out http://hueniverse.com/oauth/guide/terminology/

**Comment by hueniverse** [comment]
Why use oz at all for client-server auth? Just use hawk directly.

**Comment by patchthecode** [comment]
Don't flame me for my extremely noobish question, but I am just a programmer trying to:

1. Make sense of all the authentication stuff
2. Understand how `Oz`, `Iron` and `Hawk` work together.
3. Find out which of the Tri (`Oz`, `hawk`, `Iron`) I should be using and when.

I am an ok coder for non-web related stuff, but I'm no security expert.
After seeing your F* OAuth video, I figured that one of the instrumental devs on OAuth must have had a point, so i'm here checking out this repo. 

I have an iOS app where users can sign in. I have a server, and I have a database where user-login info/data is stored. From the way you responded to @shawm11, I guess that:

1. The type of setup I have is considered a 2-legged workflow 
2. and that `Hawk` is the one (of the trio) I should be using if my workflow is only 2-legged?

If this is true then when is `Iron` needed?
Thanks.

**Comment by hueniverse** [comment]
@patchthecode it's practically impossible to give you quality advice on this. There are just so many ways to mess things up here. Both oz and hawk are useful for app to server communication. The right solution depends on how you manage access, what your users use to login, etc. For example, if they enter a username and password on the app and then need to get back some token they can use to make api calls, hawk would be enough. If you don't want to do a token lookup every request, you can use iron to encode information into the token. I really can't help you beyond this. I suggest you find someone who has time to help who knows this space well. You should not design your system security based on this. Good luck.

**Comment by patchthecode** [comment]
Understood. And thanks for your work.
