### ISSUE TITLE
Desktop/mobile flow

### ISSUE THREAD

**Issue by mikalai-silivonik** [hueniverse/oz#45]
The [current version](https://github.com/hueniverse/oz/releases/tag/v4.0.0) of Oz is best suited for server-to-server auth, because it uses redirect flow.

Previously you [mentioned](http://hueniverse.com/2015/09/19/auth-to-see-the-wizard-or-i-wrote-an-oauth-replacement/):

> Right now Oz provides an OAuth 1.0-like workflow, but more workflows (especially for mobile) will be added soon. 

Any update on that matter? 

Thanks for the great repo, BTW!

**Comment by hueniverse** [comment]
Not yet. I'll work on it as I need it which as you can see from the history of this repo is unpredictable...
