### ISSUE TITLE
Securing app secret on client

### ISSUE THREAD

**Issue by mikalai-silivonik** [hueniverse/oz#46]
An app secret is used to sing requests to server. Once app secret is exposed, a third party can use it to perform requests on behalf of another app.

I've read your [post](http://hueniverse.com/2010/09/02/all-this-twitter-oauth-security-nonsense/) about Twitter revoking exposed secrets and got your idea:

> If Twitter uses the client secret in installed application for anything other than gathering statistics, well, they should **reconsider**. But it’s not like they have other alternative. 

As far as I understand you, that's fine that an app secret is exposed (it's really not hard to do for mobile apps, for example) as long as server is built with an assumption that that can happen.

Anything changed since 2010? Does Oz addresses the issue in any way? Or it's still better to go _proxy_ way and keep the secret in there?

**Comment by hueniverse** [comment]
Nope. There is  no way to protect client-side secrets. All you can do is issue session-specific credentials via user involvement so that there is some extra sanity but beyond that, nope.
