### ISSUE TITLE
Validate app credentials before issuing access delegation tickets

### ISSUE THREAD

**Issue by rs22** [hueniverse/oz#47]
I have a question about delegating access to other applications.

From my understanding, if App A wants to delegate access to App B, it will request a new ticket from the 'reissue'-endpoint, stating that it should be issued to App B. App A will then transfer this ticket to App B.

Now when App B starts making requests using the ticket, its App credentials were never actually verified. In other words: It is up to App A to verify the identity of App B when it transfers the delegated access ticket. If it fails to do so, anyone could make requests in the name of App B.

Wouldn't it make sense to have an rsvp-like workflow instead? App A would only request an 'access delegation'-rsvp instead of the actual ticket, which it then transfers to what it assumes is App B. To get the actual ticket from the rsvp, App B would have to obtain an app token first. Now App B could even prove its identity to App A by responding with some key stored in the original token (e.g. in ext.public).

**Comment by hueniverse** [comment]
I like this.
