### ISSUE TITLE
Oz.client.Connection in browser

### ISSUE THREAD

**Issue by richardolsson** [hueniverse/oz#53]
I've been having issues using the `Oz.client.Connection()` utility in the browser. At first I was getting weird errors from Wreck because the stream was closed to soon. Then, after I upgraded to the latest Browserify I stopped getting any callbacks from `request()` at all (although the requests properly execute and are responded to according to the developer tools' network panel).

Is using `Oz.client.Connection()` intended to work in the browser, or has that use case intentionally been ruled out?

**Comment by hueniverse** [comment]
You don't need `Oz.client` in the browser. You just need to use the **hawk** browser code directly. I have no idea about using it with browerify. I would never try that.

**Comment by richardolsson** [comment]
Thank you for your swift reply!

Maybe I'm missing something, but isn't `Oz.client.Connection` intended to help with the entire lifecycle, ticket reissue workflow, et c? Are you saying that should never happen in the browser, even for a client-side only application?

Other than the fact that app keys would not be secret in a browser app, I don't as of yet see why the entire workflow couldn't happen directly in the browser. Please help me understand.

**Comment by hueniverse** [comment]
In theory it could, but it was written for node, not the browser. If you are going to use it in the browser, you are on your own. I don't use it on the browser, I have my own browser logic code to handle it which I cannot share because it's too integrated into our logic. We just use hawk directly.

**Comment by richardolsson** [comment]
Thanks for the update. I'm thinking `Oz.client.Connection` would be very useful in any setting, including the browser. Would you consider accepting a PR which solves this? Using the node `http`/`https` modules generally works fine with tools like Browserify, so I'm guessing the issue is somewhere in the way Wreck uses these modules, and could be remedied either by small changes to Wreck or using `http`/`https` directly in `Oz.client.Connection`.

**Comment by hueniverse** [comment]
Probably not. I am not a fan of using browserify.

**Comment by AJamesPhillips** [comment]
@richardolsson I haven't got to the bottom of my dependency management (using webpack to bundle) but it seems that you can successfully require 'oz/lib/client' and use in the browser but mine is incorrectly pulling in an old version of hawk (v3.x) whose `Hawk.client.authenticate` method returns a boolean as opposed to the requirement of Oz v4 to use `Hawk.client.authenticate` v6.x.x which accepts a 5th argument of a callback.  Thus calls to `new OzClient.Connection({uri, credentials})..request("/protected", user_ticket, {}, (err, result, code, ticket) => {// never reached});`  That might be the problem you're experiencing?  Anyway, if I can't iron (no pun intended ;) ) it out I will follow hueniverse's advice and build my own wrapper around hawk.  As you said it would be nice to reuse the work hueniverse has put into the client.Connection helper.
