### ISSUE TITLE
How does delegation work?

### ISSUE THREAD

**Issue by bmdako** [hueniverse/oz#58]
Hi,

I cannot get delegation to work and I don't understand what I have to do.
I'm currently here:

1. The user has a ticket to App A.
2. The App A makes a request to the server on enpoint `/reissue` with _issueTo_ to the App B identifier. (The request is authenticated with user ticket.)
3. App A receives a new ticket with _app_ and _dlg_ that reflects the delegation.

Now I'm stuck. I've tried several thing. I.e. to send the delegated ticket to App B by _HTTP POST_. And then from App B use that ticket to authenticate with the server. But the server keeps responding Unauthorized.

What is the correct usage?

I know that @rs22 has proposed a rsvp-based delegation flow. ( https://github.com/hueniverse/oz/pull/48) But I'm simply wondering how the delegation should work on the current Oz release.

**Comment by hueniverse** [comment]
The flow is correct but make sure app B passes the correct app and dlg options when creating the header. The goal is to make sure app B doesn't get handled any random credentials and then use them. It must know what these credentials are for and where they came from.
